### PR TITLE
PP-6992: Replace FCO logo with FCDO

### PR DESCRIPTION
**Pull request by oswaldquek**
Currently looks like below but it's not ideal as a custom FCDO css class needed to be provided
Screenshot 2020-09-01 at 16 52 46

### CODE REVIEW

**Comment by oswaldquek** [comment]
When scaled down (for mobile) it looks like
Screenshot 2020-09-01 at 17 11 35

**Comment by oswaldquek** [comment]
Its a bit weird

**Comment by oswaldquek** [comment]
When using the standard css style provided:
Screenshot 2020-09-01 at 16 13 23

**Comment by iqbalgds** [comment]
I have created this PR instead: https://github.com/alphagov/pay-product-page/pull/265

**Pull request closed without merging**
