### PR TITLE
BAU: Bump rack to patch vulnerability

### PR DESCRIPTION
**Pull request by katstevens**
We've had to pin rack to 2.1.4 due to the issue mentioned below in the Gemfile. However there's now a patch version available to fix the vulnerability in https://app.snyk.io/org/govuk-pay/project/734af561-50ca-460f-bcc0-7ef1974e4b88.

I've run the build command locally and the middleman site seems fine.

### CODE REVIEW

**Comment by jfharden** [comment]
The issue says it's fixed now in 4.3.6, so worth testing if we can just unpin it?

**Comment by katstevens** [comment]
> The issue says it's fixed now in 4.3.6, so worth testing if we can just unpin it?

Even better! Will give that a go, then I can unpin the dependabot config too.

**Comment by jfharden** [comment]
Hmm middleman hasn't updated. In the Gemfile if you change the middleman dependency to `>= 4.3.6` and run `bundle update middleman` that should force it to update, it should only fail if something else is constraining it (hopefully not)

**Review by jfharden — DISMISSED** [review]

**Review by SandorArpa — APPROVED** [review]
LGTM

**Pull request merged**
