### PR TITLE
PP-9885 adding pre-filled payment link to content

### PR DESCRIPTION
**Pull request by AbdirizakIdris**
- Added link to create a pre-filled payment link to content
- Added small grammar changes
- Updated how to take payment image with the new s.v.g image

### CODE REVIEW

**Review by iqbalgds — CHANGES_REQUESTED** [review]
Can you please remove the package-lock.json file from the commit.

**Comment by iqbalgds** [comment]
Changing to a draft PR.
We do not want to merge this until the new Payment link changes are LIVE.

**Review by iqbalgds — APPROVED** [review]
Do not merge until new payment links are live.

**Review by SandorArpa — APPROVED** [review]
LGTM

**Pull request merged**
